### ISSUE TITLE
upic配置不成功

### ISSUE THREAD

**Issue by hyhy01** [icret/EasyImages2.0#53]
已经通过curl上传成功
```sh
curl -F 'image=@/Users/yh/Documents/0/tpl.png' -F "token=xxxxx"  "https://pic.xxxxx.com/api/index.php"
```
但是upic配置不成功。（和配置的返回值没关，在图床上面也没见到图片）(http和https都试过)(picgo也能成功)
![iShot_2022-07-15_11 11 31](https://user-images.githubusercontent.com/12444588/179142650-ed775bfc-4b60-483e-bf4c-371f5de371cf.jpg)
![iShot_2022-07-15_11 11 51](https://user-images.githubusercontent.com/12444588/179142657-d3110ef9-5a52-409d-81d2-ed86804009b3.jpg)
![iShot_2022-07-15_11 12 19](https://user-images.githubusercontent.com/12444588/179142660-9dfcb2d9-03c0-42e9-a580-a153b3d5d5d9.jpg)
![iShot_2022-07-15_11 12 50](https://user-images.githubusercontent.com/12444588/179142661-5ce68dc2-ffb9-4cde-8c6b-b44371dbccaf.jpg)

**Comment by JJPro** [comment]
@hyhy01 @icret  Holy shit, I got it working in uPic. 

<img width="465" alt="image" src="https://user-images.githubusercontent.com/871037/188062026-ae5583c5-5488-4ee7-9048-511e670efba5.png">

You have to specify `Content-Type` as `multipart/form-data` in request header. Otherwise, it will send the data, including the file, as pure JSON. 

---

### The following is my debug journey and postmortem:

First, I checked nginx log to make sure that the server is getting the request. And that's a check. 
Then I want to see what the server returns to uPic like so: 
I captured traffic with `tcpdump`, then used **Wireshark** to analyze the traffic. 
There, I can see that server sends the following json back: 
```json
{
    "result": "failed",
    "code": 204,
    "message": "没有选择上传的文件"
}
```
Hmmm, interesting. 

Then I analyzed traffic via `curl` and **Postman** as well for comparison. 
There I can see that, both `curl` and **Postman** is sending the request as type `multipart/form-data`, while **uPic** is doing that via `application/json`, which is a sub-type of `html/text`. 
Aha! I was like, WHAT?! uPic, how dare you send a file via `json`. 

这件事对于开发人员的经验/教训: 
When sending a file, never forget to attach header `Content-type: multipart/form-data` to the request.
